/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NoteListItem {
  'id' : bigint,
  'title' : string,
  'isUpvotedByMe' : boolean,
  'upvoteCount' : bigint,
  'subject' : Subject,
  'isBookmarkedByMe' : boolean,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'description' : string,
  'author' : Principal,
  'updatedAt' : bigint,
}
export interface NoteListResult {
  'notes' : Array<NoteListItem>,
  'nextCursor' : [] | [bigint],
}
export interface NoteResponse {
  'id' : bigint,
  'title' : string,
  'isUpvotedByMe' : boolean,
  'content' : string,
  'upvoteCount' : bigint,
  'subject' : Subject,
  'isBookmarkedByMe' : boolean,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'authorName' : string,
  'description' : string,
  'author' : Principal,
  'updatedAt' : bigint,
}
export interface ProfileWithStats {
  'name' : string,
  'createdAt' : bigint,
  'noteCount' : bigint,
  'totalUpvotesReceived' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type SortBy = { 'RecentlyUpdated' : null } |
  { 'MostUpvoted' : null } |
  { 'Newest' : null };
export type Subject = { 'Art' : null } |
  { 'Economics' : null } |
  { 'History' : null } |
  { 'ComputerScience' : null } |
  { 'Mathematics' : null } |
  { 'Music' : null } |
  { 'Philosophy' : null } |
  { 'English' : null } |
  { 'Science' : null } |
  { 'Other' : null } |
  { 'Languages' : null };
export interface UserProfile { 'name' : string, 'createdAt' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookmarkNote' : ActorMethod<[bigint], undefined>,
  'createNote' : ActorMethod<
    [string, string, string, Subject, Array<string>],
    bigint
  >,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'getAllNotes' : ActorMethod<[[] | [bigint], bigint, SortBy], NoteListResult>,
  'getBookmarkIds' : ActorMethod<[], Array<bigint>>,
  'getBookmarks' : ActorMethod<[[] | [bigint], bigint], NoteListResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNote' : ActorMethod<[bigint], [] | [NoteResponse]>,
  'getNotesBySubject' : ActorMethod<
    [Subject, [] | [bigint], bigint, SortBy],
    NoteListResult
  >,
  'getNotesByTag' : ActorMethod<
    [string, [] | [bigint], bigint],
    NoteListResult
  >,
  'getPopularTags' : ActorMethod<[bigint], Array<string>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSubjectCounts' : ActorMethod<[], Array<[Subject, bigint]>>,
  'getUserNotes' : ActorMethod<
    [Principal, [] | [bigint], bigint],
    NoteListResult
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [ProfileWithStats]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'removeUpvote' : ActorMethod<[bigint], undefined>,
  'searchNotes' : ActorMethod<
    [string, [] | [Subject], [] | [bigint], bigint],
    NoteListResult
  >,
  'setProfile' : ActorMethod<[string], undefined>,
  'updateNote' : ActorMethod<
    [bigint, string, string, string, Subject, Array<string>],
    undefined
  >,
  'upvoteNote' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];