/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.1.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'Art' : IDL.Null,
  'Economics' : IDL.Null,
  'History' : IDL.Null,
  'ComputerScience' : IDL.Null,
  'Mathematics' : IDL.Null,
  'Music' : IDL.Null,
  'Philosophy' : IDL.Null,
  'English' : IDL.Null,
  'Science' : IDL.Null,
  'Other' : IDL.Null,
  'Languages' : IDL.Null,
});
export const SortBy = IDL.Variant({
  'RecentlyUpdated' : IDL.Null,
  'MostUpvoted' : IDL.Null,
  'Newest' : IDL.Null,
});
export const NoteListItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isUpvotedByMe' : IDL.Bool,
  'upvoteCount' : IDL.Nat,
  'subject' : Subject,
  'isBookmarkedByMe' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
});
export const NoteListResult = IDL.Record({
  'notes' : IDL.Vec(NoteListItem),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const NoteResponse = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'isUpvotedByMe' : IDL.Bool,
  'content' : IDL.Text,
  'upvoteCount' : IDL.Nat,
  'subject' : Subject,
  'isBookmarkedByMe' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const ProfileWithStats = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'noteCount' : IDL.Nat,
  'totalUpvotesReceived' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookmarkNote' : IDL.Func([IDL.Nat], [], []),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Subject, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat, SortBy],
      [NoteListResult],
      ['query'],
    ),
  'getBookmarkIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getBookmarks' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Nat],
      [NoteListResult],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(NoteResponse)], ['query']),
  'getNotesBySubject' : IDL.Func(
      [Subject, IDL.Opt(IDL.Nat), IDL.Nat, SortBy],
      [NoteListResult],
      ['query'],
    ),
  'getNotesByTag' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
      [NoteListResult],
      ['query'],
    ),
  'getPopularTags' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSubjectCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Subject, IDL.Nat))],
      ['query'],
    ),
  'getUserNotes' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Nat],
      [NoteListResult],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProfileWithStats)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'removeUpvote' : IDL.Func([IDL.Nat], [], []),
  'searchNotes' : IDL.Func(
      [IDL.Text, IDL.Opt(Subject), IDL.Opt(IDL.Nat), IDL.Nat],
      [NoteListResult],
      ['query'],
    ),
  'setProfile' : IDL.Func([IDL.Text], [], []),
  'updateNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Subject, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'upvoteNote' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'Art' : IDL.Null,
    'Economics' : IDL.Null,
    'History' : IDL.Null,
    'ComputerScience' : IDL.Null,
    'Mathematics' : IDL.Null,
    'Music' : IDL.Null,
    'Philosophy' : IDL.Null,
    'English' : IDL.Null,
    'Science' : IDL.Null,
    'Other' : IDL.Null,
    'Languages' : IDL.Null,
  });
  const SortBy = IDL.Variant({
    'RecentlyUpdated' : IDL.Null,
    'MostUpvoted' : IDL.Null,
    'Newest' : IDL.Null,
  });
  const NoteListItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isUpvotedByMe' : IDL.Bool,
    'upvoteCount' : IDL.Nat,
    'subject' : Subject,
    'isBookmarkedByMe' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
  });
  const NoteListResult = IDL.Record({
    'notes' : IDL.Vec(NoteListItem),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const NoteResponse = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'isUpvotedByMe' : IDL.Bool,
    'content' : IDL.Text,
    'upvoteCount' : IDL.Nat,
    'subject' : Subject,
    'isBookmarkedByMe' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'createdAt' : IDL.Int });
  const ProfileWithStats = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'noteCount' : IDL.Nat,
    'totalUpvotesReceived' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookmarkNote' : IDL.Func([IDL.Nat], [], []),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Subject, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat, SortBy],
        [NoteListResult],
        ['query'],
      ),
    'getBookmarkIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getBookmarks' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [NoteListResult],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(NoteResponse)], ['query']),
    'getNotesBySubject' : IDL.Func(
        [Subject, IDL.Opt(IDL.Nat), IDL.Nat, SortBy],
        [NoteListResult],
        ['query'],
      ),
    'getNotesByTag' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Nat],
        [NoteListResult],
        ['query'],
      ),
    'getPopularTags' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSubjectCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Subject, IDL.Nat))],
        ['query'],
      ),
    'getUserNotes' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Nat],
        [NoteListResult],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProfileWithStats)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'removeUpvote' : IDL.Func([IDL.Nat], [], []),
    'searchNotes' : IDL.Func(
        [IDL.Text, IDL.Opt(Subject), IDL.Opt(IDL.Nat), IDL.Nat],
        [NoteListResult],
        ['query'],
      ),
    'setProfile' : IDL.Func([IDL.Text], [], []),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Subject, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'upvoteNote' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };