/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NoteListResult {
    notes: Array<NoteListItem>;
    nextCursor?: bigint;
}
export interface NoteResponse {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    content: string;
    upvoteCount: bigint;
    subject: Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
}
export interface NoteListItem {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    upvoteCount: bigint;
    subject: Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ProfileWithStats {
    name: string;
    createdAt: bigint;
    noteCount: bigint;
    totalUpvotesReceived: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface UserProfile {
    name: string;
    createdAt: bigint;
}
export enum SortBy {
    RecentlyUpdated = "RecentlyUpdated",
    MostUpvoted = "MostUpvoted",
    Newest = "Newest"
}
export enum Subject {
    Art = "Art",
    Economics = "Economics",
    History = "History",
    ComputerScience = "ComputerScience",
    Mathematics = "Mathematics",
    Music = "Music",
    Philosophy = "Philosophy",
    English = "English",
    Science = "Science",
    Other = "Other",
    Languages = "Languages"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __accessControlState(): Promise<any>;
    __nextNoteId(): Promise<bigint>;
    __noteUpvoters(): Promise<any>;
    __notes(): Promise<any>;
    __userBookmarks(): Promise<any>;
    __userNoteCounts(): Promise<any>;
    __userProfiles(): Promise<any>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookmarkNote(id: bigint): Promise<void>;
    createNote(title: string, description: string, content: string, subject: Subject, tags: Array<string>): Promise<bigint>;
    deleteNote(id: bigint): Promise<void>;
    getAllNotes(cursor: bigint | null, limit: bigint, sort: SortBy): Promise<NoteListResult>;
    getBookmarkIds(): Promise<Array<bigint>>;
    getBookmarks(cursor: bigint | null, limit: bigint): Promise<NoteListResult>;
    getCallerUserRole(): Promise<UserRole>;
    getNote(id: bigint): Promise<NoteResponse | null>;
    getNotesBySubject(subject: Subject, cursor: bigint | null, limit: bigint, sort: SortBy): Promise<NoteListResult>;
    getNotesByTag(tag: string, cursor: bigint | null, limit: bigint): Promise<NoteListResult>;
    getPopularTags(limit: bigint): Promise<Array<string>>;
    getProfile(): Promise<UserProfile | null>;
    getSubjectCounts(): Promise<Array<[Subject, bigint]>>;
    getUserNotes(principal: Principal, cursor: bigint | null, limit: bigint): Promise<NoteListResult>;
    getUserProfile(principal: Principal): Promise<ProfileWithStats | null>;
    isCallerAdmin(): Promise<boolean>;
    removeBookmark(id: bigint): Promise<void>;
    removeUpvote(id: bigint): Promise<void>;
    searchNotes(searchQuery: string, subject: Subject | null, cursor: bigint | null, limit: bigint): Promise<NoteListResult>;
    setProfile(name: string): Promise<void>;
    updateNote(id: bigint, title: string, description: string, content: string, subject: Subject, tags: Array<string>): Promise<void>;
    upvoteNote(id: bigint): Promise<void>;
}
import type { Error as _Error, NoteListItem as _NoteListItem, NoteListResult as _NoteListResult, NoteResponse as _NoteResponse, ProfileWithStats as _ProfileWithStats, Result as _Result, SortBy as _SortBy, Subject as _Subject, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __nextNoteId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextNoteId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextNoteId();
            return result;
        }
    }
    async __noteUpvoters(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__noteUpvoters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__noteUpvoters();
            return result;
        }
    }
    async __notes(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__notes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__notes();
            return result;
        }
    }
    async __userBookmarks(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__userBookmarks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userBookmarks();
            return result;
        }
    }
    async __userNoteCounts(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__userNoteCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userNoteCounts();
            return result;
        }
    }
    async __userProfiles(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__userProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__userProfiles();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookmarkNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookmarkNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookmarkNote(arg0);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: string, arg3: Subject, arg4: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, arg2, to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, arg2, to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async getAllNotes(arg0: bigint | null, arg1: bigint, arg2: SortBy): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_SortBy_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_SortBy_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookmarkIds(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarkIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarkIds();
            return result;
        }
    }
    async getBookmarks(arg0: bigint | null, arg1: bigint): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: bigint): Promise<NoteResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesBySubject(arg0: Subject, arg1: bigint | null, arg2: bigint, arg3: SortBy): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesBySubject(to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_SortBy_n10(this._uploadFile, this._downloadFile, arg3));
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesBySubject(to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_SortBy_n10(this._uploadFile, this._downloadFile, arg3));
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesByTag(arg0: string, arg1: bigint | null, arg2: bigint): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByTag(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByTag(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPopularTags(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPopularTags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPopularTags(arg0);
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectCounts(): Promise<Array<[Subject, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectCounts();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectCounts();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserNotes(arg0: Principal, arg1: bigint | null, arg2: bigint): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserNotes(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserNotes(arg0, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<ProfileWithStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBookmark(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBookmark(arg0);
            return result;
        }
    }
    async removeUpvote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUpvote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUpvote(arg0);
            return result;
        }
    }
    async searchNotes(arg0: string, arg1: Subject | null, arg2: bigint | null, arg3: bigint): Promise<NoteListResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotes(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotes(arg0, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_NoteListResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(arg0);
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Subject, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, to_candid_Subject_n7(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async upvoteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvoteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvoteNote(arg0);
            return result;
        }
    }
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_NoteListItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteListItem): NoteListItem {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NoteListResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteListResult): NoteListResult {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NoteResponse_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteResponse): NoteResponse {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NoteResponse]): NoteResponse | null {
    return value.length === 0 ? null : from_candid_NoteResponse_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileWithStats]): ProfileWithStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: Array<_NoteListItem>;
    nextCursor: [] | [bigint];
}): {
    notes: Array<NoteListItem>;
    nextCursor?: bigint;
} {
    return {
        notes: from_candid_vec_n14(_uploadFile, _downloadFile, value.notes),
        nextCursor: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    upvoteCount: bigint;
    subject: _Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
}): {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    upvoteCount: bigint;
    subject: Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        isUpvotedByMe: value.isUpvotedByMe,
        upvoteCount: value.upvoteCount,
        subject: from_candid_Subject_n17(_uploadFile, _downloadFile, value.subject),
        isBookmarkedByMe: value.isBookmarkedByMe,
        createdAt: value.createdAt,
        tags: value.tags,
        authorName: value.authorName,
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    content: string;
    upvoteCount: bigint;
    subject: _Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
}): {
    id: bigint;
    title: string;
    isUpvotedByMe: boolean;
    content: string;
    upvoteCount: bigint;
    subject: Subject;
    isBookmarkedByMe: boolean;
    createdAt: bigint;
    tags: Array<string>;
    authorName: string;
    description: string;
    author: Principal;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        isUpvotedByMe: value.isUpvotedByMe,
        content: value.content,
        upvoteCount: value.upvoteCount,
        subject: from_candid_Subject_n17(_uploadFile, _downloadFile, value.subject),
        isBookmarkedByMe: value.isBookmarkedByMe,
        createdAt: value.createdAt,
        tags: value.tags,
        authorName: value.authorName,
        description: value.description,
        author: value.author,
        updatedAt: value.updatedAt
    };
}
function from_candid_tuple_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Subject, bigint]): [Subject, bigint] {
    return [
        from_candid_Subject_n17(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Art: null;
} | {
    Economics: null;
} | {
    History: null;
} | {
    ComputerScience: null;
} | {
    Mathematics: null;
} | {
    Music: null;
} | {
    Philosophy: null;
} | {
    English: null;
} | {
    Science: null;
} | {
    Other: null;
} | {
    Languages: null;
}): Subject {
    return "Art" in value ? Subject.Art : "Economics" in value ? Subject.Economics : "History" in value ? Subject.History : "ComputerScience" in value ? Subject.ComputerScience : "Mathematics" in value ? Subject.Mathematics : "Music" in value ? Subject.Music : "Philosophy" in value ? Subject.Philosophy : "English" in value ? Subject.English : "Science" in value ? Subject.Science : "Other" in value ? Subject.Other : "Languages" in value ? Subject.Languages : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoteListItem>): Array<NoteListItem> {
    return value.map((x)=>from_candid_NoteListItem_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Subject, bigint]>): Array<[Subject, bigint]> {
    return value.map((x)=>from_candid_tuple_n27(_uploadFile, _downloadFile, x));
}
function to_candid_SortBy_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject | null): [] | [_Subject] {
    return value === null ? candid_none() : candid_some(to_candid_Subject_n7(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    RecentlyUpdated: null;
} | {
    MostUpvoted: null;
} | {
    Newest: null;
} {
    return value == SortBy.RecentlyUpdated ? {
        RecentlyUpdated: null
    } : value == SortBy.MostUpvoted ? {
        MostUpvoted: null
    } : value == SortBy.Newest ? {
        Newest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    Art: null;
} | {
    Economics: null;
} | {
    History: null;
} | {
    ComputerScience: null;
} | {
    Mathematics: null;
} | {
    Music: null;
} | {
    Philosophy: null;
} | {
    English: null;
} | {
    Science: null;
} | {
    Other: null;
} | {
    Languages: null;
} {
    return value == Subject.Art ? {
        Art: null
    } : value == Subject.Economics ? {
        Economics: null
    } : value == Subject.History ? {
        History: null
    } : value == Subject.ComputerScience ? {
        ComputerScience: null
    } : value == Subject.Mathematics ? {
        Mathematics: null
    } : value == Subject.Music ? {
        Music: null
    } : value == Subject.Philosophy ? {
        Philosophy: null
    } : value == Subject.English ? {
        English: null
    } : value == Subject.Science ? {
        Science: null
    } : value == Subject.Other ? {
        Other: null
    } : value == Subject.Languages ? {
        Languages: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
